services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./content:/foo
    environment:
      - SWAGGER_JSON=/foo/cheatsheet.yaml

networks:
  default:
    name: ${NETWORK}
    external: true
