openapi: 3.0.3
info:
  title: Cheatsheet API
  description: Cheatsheet API
  version: 1.0.0
servers:
  - url: 'https://cheatsheet-backend.taundinhle.com/api'
paths:
  /auth/login:
    post:
      tags:
        - Authenticate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'

  /cheatsheets:
    get:
      tags:
        - Cheatsheet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheatsheets'


components:
  schemas:
    Login:
      type: object
      properties:
        user_id:
          type: string
        access_token:
          type: string
    401:
      type: object
      properties:
        message:
          type: string
          enum: [ 'Unauthenticated' ]
    Cheatsheets:
      type: object
      properties:
        total:
          type: integer
        currentPage:
          type: integer
        lastPage:
          type: integer
        perPage:
          type: integer
        nextPageUrl:
          type: string
        prevPageUrl:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Cheatsheet'

    Cheatsheet:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        categoryId:
          type: string
        icon:
          type: string
