openapi: 3.0.3
info:
  title: Cheatsheet API
  description: Cheatsheet API
  version: 1.0.0
servers:
  - url: 'https://cheatsheet-backend.taundinhle.com/api'
paths:
  /auth/login:
    post:
      tags:
        - Authenticate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'

  /logout:
    delete:
      tags:
        - Authenticate
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /cheatsheets:
    get:
      tags:
        - Cheatsheet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheatsheets'
    post:
      tags:
        - Cheatsheet
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                languageId:
                  type: integer
                groupId:
                  type: integer
                icon:
                  type: integer
              required:
                - name
                - languageId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  category_id:
                    type: string
                    nullable: true
                  user_id:
                    type: string
                  language_id:
                    type: string
                  uuid:
                    type: string
                  updated_at:
                    type: string
                  created_at:
                    type: string


  /chcheatsheets/{uuid}:
    get:
      tags:
        - Cheatsheet
      parameters:
        - name: uuid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheatsheet Detail'


          #  /cheatsheets: post

  /languages:
    get:
      tags:
        - Languages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    uuid:
                      type: string
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string

  /categories:
    get:
      tags:
        - Categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    uuid:
                      type: string
                    name:
                      type: string

  /user:
    get:
      tags:
        - User
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    Login:
      type: object
      properties:
        user_id:
          type: string
        access_token:
          type: string

    401:
      type: object
      properties:
        message:
          type: string
          enum: [ 'Unauthenticated' ]

    Cheatsheets:
      type: object
      properties:
        total:
          type: integer
        currentPage:
          type: integer
        lastPage:
          type: integer
        perPage:
          type: integer
        nextPageUrl:
          type: string
        prevPageUrl:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Cheatsheet'

    Cheatsheet:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        categoryId:
          type: number
        icon:
          type: string

    Cheatsheet Detail:
      type: object
      properties:
        cheatsheetDetail:
          type: object
          properties:
            uuid:
              type: string
            title:
              type: string
            position:
              type: string
            cheatsheetUUid:
              type: string
            cheatsheetCards:
              type: array
              items:
                $ref: '#/components/schemas/Cheatsheet Card'

    Cheatsheet Card:
      type: object
      properties:
        uuid:
          type: string
        title:
          type: string
        note:
          type: string
          nullable: true
        topicUUid:
          type: string
        cheatsheetCardDetail:
          type: array
          items:
            $ref: '#/components/schemas/Cheatsheet Card Detail'

    Cheatsheet Card Detail:
      type: object
      properties:
        uuid:
          type: string
        title:
          type: string
          nullable: true
        content:
          type: string
        position:
          type: string
        displayTypeCode:
          type: string
        cheatsheetCardUUid:
          type: string

    User:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
        updated_at:
          type: string
        user_profile:
          $ref: '#/components/schemas/User Profile'

    User Profile:
      type: object
      properties:
        avatar:
          type: string
        updated_at:
          type: string

  securitySchemes:
    Bearer Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT