name: Swagger

run-name: Build

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SERVER_HOST
        env:
          SERVER_HOST: '${{ secrets.SERVER_HOST }}'
        run: echo $SERVER_HOST
      - name: SERVER_USERNAME
        run: echo ${{ secrets.SERVER_USERNAME }}
      - name: SSH_PRIVATE_KEY
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            mkdir test
