name: Swagger

run-name: Deploy Production

on:
  push:

jobs:
  Deploy_Production:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_REPOSITORY: $$GITHUB_REPOSITORY
          GITHUB_HEAD_REF: $$GITHUB_HEAD_REF
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_REPOSITORY,GITHUB_HEAD_REF
          script: |
            source .zshrc
            source $PATH_ENVIRONTMENT/.github-action
            cd $SWARM_HOME/$GITHUB_REPOSITORY
            git checkout $GITHUB_HEAD_REF
            docker compose down 
            docker compose up -d
